apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    app: myapp
    env: production
    version: v1
    author: ghouse-rizvi
    annotation: This is a sample pod with labels and annotations
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80