apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
    - type: Container
      max:
        cpu: "500m"
        memory: "128Mi"
      min:
        cpu: "250m"
        memory: "64Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      # resources:
      #   requests:
      #     memory: "64Mi"
      #     cpu: "250m"
      #   limits:
      #     memory: "128Mi"
      #     cpu: "500m"
