apiVersion: v1
kind: Pod
metadata:
  name: my-pod-config
spec:
  containers:
    - name: my-container
      image: nginx:latest
      envFrom:
        - configMapRef:
            name: my-config
        - secretRef:
            name: my-secret