apiVersion: v1
kind: Pod
metadata:
  name: stress

spec:
  containers:
    - image: polinux/stress
      imagePullPolicy: always
      name: stress
      command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"] 
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"