apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:latest
    command: ["sleep", "10"]
    
 