apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  # Base64 encoded values
  username: Z2hvdXNlcml6dmk= # Base64 encoded value of "username"
  password: cGFzc3dvcmQ=  # Base64 encoded value of "password"
  api-token: YXBpLXRva2Vu  # Base64 encoded value of "api-token"
  db-connection-string: ZGItY29ubmVjdGlvbi1zdHJpbmc=  # Base64 encoded value of "db-connection-string"